### PR TITLE
Added links , definitions 

### PR DESCRIPTION
**Pull request by shaonakundu**
I have contributed to many questions like for acronyms I hav added few of them and described them too, Also I have added links and definitions for backend questions category. Hope you like it. Do let me know and it was fun to contribute.

### CODE REVIEW

**Comment by shaonakundu** [comment]
Hey can you let me know why is it showing conflicts?

**Comment by oyakhilomee** [comment]
@shaonakundu from looking at the code you contributed, I think adding links might not be what is needed in those cases. You're supposed to define the questions with answers and not put in links I think.

**Comment by shaonakundu** [comment]
> @shaonakundu from looking at the code you contributed, I think adding links might not be what is needed in those cases. You're supposed to define the questions with answers and not put in links I think.

Actually it was mentioned that if descriptions are not short then links to be added

**Comment by shaonakundu** [comment]
> > @shaonakundu from looking at the code you contributed, I think adding links might not be what is needed in those cases. You're supposed to define the questions with answers and not put in links I think.
> 
> Actually it was mentioned that if descriptions are not short then links to be added

@VickiLanger can you please once clarify

**Comment by oyakhilomee** [comment]
@shaonakundu I think you should try answering them a little bit then add a link at the end.

**Comment by shaonakundu** [comment]
> @shaonakundu I think you should try answering them a little bit then add a link at the end.

ok ok thank you

**Comment by shaonakundu** [comment]
> > @shaonakundu I think you should try answering them a little bit then add a link at the end.
> 
> ok ok thank you

I guess still conflicts are there even after adding lines with link

**Comment by VickiLanger** [comment]
@shaonakundu links are good if the answer is too long or too complex to keep short. As for the conflicts, I'll take a look

**Review by VickiLanger — APPROVED** [review]
All fantastic answers. Thank you for contributing. I will merge this as soon as I figure out what to do with the conflicts.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/CodeQBot) to see the hard work you put in.*

**Comment by shaonakundu** [comment]
> All fantastic answers. Thank you for contributing. I will merge this as soon as I figure out what to do with the conflicts.
> 
> _Don't forget to follow the bot on [Twitter](https://www.twitter.com/CodeQBot) to see the hard work you put in._

Thank you. Glad you liked them

**Pull request merged**
