### PR TITLE
Update tweet.py

### PR DESCRIPTION
**Pull request by achoudh5**
For Issue #8
- I have put my code in comments, hope that's the right place
- Used TweepError
- Tried f string in line 47, I hope syntax is fine, if not I can change to a normal concatenation format
- Added reference link in `line 45`

### CODE REVIEW

**Review by VickiLanger — APPROVED** [review]
Looks great! Thanks for your contribution!

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/codqbot) to see the hard work you put in.*

**Comment by achoudh5** [comment]
> Looks great! Thanks for your contribution.
> 
> _Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in._

@VickiLanger If you don't mind can you please add `hacktoberfest-accepted` label just for my usecase :)

**Comment by VickiLanger** [comment]
@achoudh5 Can do. I added it, but I don't think it's required. Since I merged your request, the label isn't necassary.

Screen Shot from hacktoberfest site: PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)

**Comment by achoudh5** [comment]
> @achoudh5 Can do. I added it, but I don't think it's required. Since I merged your request, the label isn't necassary.
> 
> Screen Shot from hacktoberfest site: PRs count if: Submitted in a repo with the hacktoberfest topic AND during the month of October AND ( The PR is merged OR The PR is labelled as hacktoberfest-accepted by a maintainer OR The PR has been approved )

You are right for sure, I am gonna make a prject to fetch all PRs with `hacktoberfest-accepted` . To start with I know it's working when I see mine in it haha. Thanks again, appreciate that....I am going to enjoy fall colors in NC for few days now before this project 😎

**Comment by VickiLanger** [comment]
Sounds like a good project. Have fun

**Pull request merged**
